### PR TITLE
Add token bearer for swagger

### PR DESCRIPTION
**Pull request by shadowmodder**
1. Add token bearer to swagger
2. fix swagger request URL

### CODE REVIEW

**Comment by shadowmodder** [comment]
@AnandChowdhary  plz review

**Comment by AnandChowdhary** [comment]
Is there no way to globally add `@ApiBearerAuth`? Because we support both API keys and access token, and this PR only adds access tokens, right?

**Comment by shadowmodder** [comment]
I checked nestjs/swagger docs, I don't see any other way to add `@ApiBearerAuth` globally, If you see any references please share.
Actually, the bearer token is working for both API keys and access tokens.

**Comment by FindingAnand** [comment]
⚠️ This PR has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Pull request closed without merging**
